---
title: "hw_5"
author: "Таисия Метелкина"
date: '26 февраля 2019 г '
output: html_document
---


### 5.1
```{r setup, include=FALSE}
library(ca)
library (ggplot2)
library(tidyverse)

chairs <- read.csv ('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/tsmetelkina/hw5_CA_MCA/hw5_chairs.csv')
MCA <- MASS::mca(chairs[,-(1:3)])
chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)
chairs %>% 
  ggplot(aes(`1`, `2`)) +
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names), size = 3)+
  theme_bw() +
  scale_x_continuous(limits = c(-0.015, 0.02))

```
### 5.2
```{r setup, include=FALSE}
И Sessel, и Stuhl обладают некоторым набором характеризующих их признаков. По графику видно, что Sessel и Stuhl описывают два разных, но оладающих общими характеристиками предмета (т.е. это две отдельные категории, имеющие некоторые общие свойства). 
Некоторые переменные относятся только к какой-то одной из этих категорий (например, регулируемая спинка и способность катиться -- для стула vs. доп. функция: кровать или способность качаться -- для кресла). 
Также некоторые переменные, отображаемые рядом друг с другом на графике, позволяют выделять подкатегории кресел и стульев, например, металлический обеденный стол с низкой спинкой и без ручек vs. крутяще-катящийся рабочий стул с регулировкой высоты; обычное кресло с высокой спинкой и подлокотниками vs. кресло-качалка.
```

### 5.3
```{r setup, include=FALSE}
colours <- read.csv ('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/tsmetelkina/hw5_CA_MCA/hw5_colreg.csv')
rownames(colours) <- colours$color
ca <- ca(colours[-5])
colours_col <- data.frame(ca$colcoord)
colours_col$rows <- rownames(ca$colcoord)

colours_row <- data.frame(ca$rowcoord)
colours_row$rows <- rownames(ca$rowcoord)

colours_col %>% 
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "blue")+
  geom_text(data = colours_row, color = "red")+
  theme_bw()+
  labs(x = "Dim1 (42.1%)",
       y = "Dim2 (32.6%)") +
    scale_x_continuous(limits = c(-2.5, 2.5))
```
### 5.4
```{r setup, include=FALSE}
Названия цветов неравномерно распределены между текстами разных жанров: для художественной литературы (fiction) характерно большее разнообразие названий цветов, чем для других жанров. Для научных текстов (academic) употребление названий цветов не характерно (чаще всего употребляются белый и чёрный, встречающиеся во всех жанрах). Красный (рыжий), зелёный и оранжевый более характерны для описываемого в прессе (press); синий, жёлтый, розовый, фиолетовый, коричневый и серый -- для художественной литеатуры. Чёрный, несмотря на то, что наряду с белым часто используется во всех жанрах, наиболее характерен для разговорной речи (spoken). Наиболее различающимися друг от друга по употреблению названий цветов в адъективной функции жанрами являются научные тексты и художественная литература.
```
